= Database Studio Configuration - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../assets/images/


To configure a connector in Anypoint Studio:

. Add the connector to a project.
. Configure the connector.
. Configure an input source for the connector.

== Add the Connector to a Studio Project

Anypoint Studio provides two ways to add the connector to your Studio project: from the Exchange button in the Studio taskbar or from the Mule Palette view.

=== Add the Connector Using Exchange

. In Studio, create a Mule project.
. Click the Exchange icon *(X)* in the upper-left of the Studio task bar.
. In Exchange, click *Login* and supply your Anypoint Platform username and password.
. In Exchange, search for "db".
. Select the connector and click *Add to project*.
. Follow the prompts to install the connector.

=== Add the Connector in Studio

. In Studio, create a Mule project.
. In the Mule Palette view, click *(X) Search in Exchange*.
. In *Add Modules to Project*, type "db" in the search field.
. Click this connector's name in *Available modules*.
. Click *Add*.
. Click *Finish*.

== Configure the Connector

No additional configuration is required. Optionally, you can https://docs.mulesoft.com/mule-runtime/4.1/global-settings-configuration[configure global properties] for this connector.

== Configure an Input Source

Configure an input source for the connector such as a connector operation,
using *HTTP Listener*, or *Scheduler*.

You can put the following operations for the connector in the *Source* area
of the Studio canvas.

* `On table row`


== See Also

https://help.mulesoft.com[MuleSoft Help Center]
